config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
    get '/login' => 'login#login', :as => :login
    get '/login/google', to: redirect('auth/google_oauth2'), as: :google_login
    get '/login/github', to: redirect('auth/github'), as: :github_login
    get '/auth/google_oauth2/callback', to: 'login#google_oauth2', as: :google_oauth2_callback
    get '/auth/github/callback', to: 'login#github', as: :github_callback
    get '/logout' => 'login#logout', :as => :logout
    get '/user/profile', to: 'user#profile', as: :user_profile

    root to: 'map#index', as: 'root'
    get '/state/:state_symbol' => 'map#state', :as => :state_map
    get '/state/:state_symbol/county/:std_fips_code' => 'map#county', :as => :county
    get '/ajax/state/:state_symbol' => 'ajax#counties'

    # Routes for Events
    resources :events, only: %i[index show]
    get '/my_events/new' => 'my_events#new', :as => :new_my_event
    match '/my_events/new', to: 'my_events#create', via: [:post]
    get '/my_events/:id' => 'my_events#edit', :as => :edit_my_event
    match '/my_events/:id', to: 'my_events#update', via: %i[put patch]
    match '/my_events/:id', to: 'my_events#destroy', via: [:delete]

    # Routes for Representatives
    resources :representatives, only: [:index]
    resources :representatives do
        resources :news_items, only: %i[index show]
        # get '/representatives/:representative_id/my_news_item/new' => 'my_news_items#select_rep_issue', 
        #                                                            => :select_rep_issue #v3
        get '/representatives/:representative_id/my_news_item/new' => 'my_news_items#new', 
            :as                                                        => :new #v1
        # get '/representatives/:representative_id/my_news_item/new/search' => 'my_news_items#search',
        #     :as                                                        => :search #v3
        post '/representatives/:representative_id/my_news_item/new' => 'my_news_items#search',
        :as                                                        => :search #v1
        get '/representatives/:representative_id/my_news_item/new/top_articles' => 'my_news_items#top_articles',
            :as                                                        => :top_articles #v1
        post '/representatives/:representative_id/my_news_item/new/top_articles' => 'my_news_items#rate_article',
            :as                                                        => :rate_article #v1
        #post '/representatives/:representative_id/my_news_item', to: 'my_news_items#create' 
    
        # get 'my_news_item/new', to: 'my_news_items#select_rep_issue', as: :select_rep_issue 
        # get 'my_news_item/new/top_articles', to: 'my_news_items#top_articles', as: :top_articles #v3
        # get 'my_news_item/new/continue', to: 'my_news_items#new_rep_issue', as: :new_rep_issue #v3
        # post 'my_news_item', to: 'my_news_items#create' #v3
  
        # get '/representatives/:representative_id/my_news_item/new' => 'my_news_items#new',
        #     :as                                                    => :new_my_news_item #v3
        #match '/representatives/:representative_id/my_news_item/new', to:  'my_news_items#create',
        #                                                              via: [:post] #v3
        get '/representatives/:representative_id/my_news_item/:id' => 'my_news_items#edit',
            :as                                                    => :edit_my_news_item #v2
        # match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#update',
        #                                                               via: %i[put patch] #v3
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#destroy',
                                                                      via: [:delete] #v2
    end
    get '/search/(:address)' => 'search#search', :as => 'search_representatives'
end

app/models/representative.rb
# frozen_string_literal: true

class Representative < ApplicationRecord
  has_many :news_items, dependent: :delete_all

  def self.create_representative(official, office_title, ocdid)
    data = representative_data(official, office_title, ocdid)
    Representative.find_or_create_by(data)
  end

  def self.civic_api_to_representative_params(rep_info)
    reps = []

    rep_info.officials.each_with_index do |official, index|
      ocdid_temp = ''
      title_temp = ''

      rep_info.offices.each do |office|
        if office.official_indices.include? index
          title_temp = office.name
          ocdid_temp = office.division_id
        end
      end

      rep = create_representative(official, title_temp, ocdid_temp)
      reps.push(rep)
    end

    reps
  end

  def self.representative_data(official, office_title, ocdid)
    if official.address
      {
        name:      official.name || '',
        title:     office_title, ocdid: ocdid,
        street:    official.address[0].line1.to_s,
        city:      official.address[0].city.to_s,
        state:     official.address[0].state.to_s,
        zip:       official.address[0].zip.to_s,
        party:     official.party, photo_url: official.photo_url
      }
    else
      {
        name:      official.name || '',
        title:     office_title, ocdid: ocdid,
        street:    'No Address Provided', city: '',
        state:     '', zip: '',
        party:     official.party, photo_url: official.photo_url
      }
    end
  end
end

app/controllers/representatives_controller.rb
# frozen_string_literal: true

class RepresentativesController < ApplicationController
  def index
    @representatives = Representative.all
  end

  def show
    @representative =  Representative.find_by(id: params[:id])
    if @representative.nil?
      flash[:alert] = 'There is no such Representative'
      redirect_to representatives_path
    else
      render :show
    end
  end
end

app/helpers/representatives_helper.rb
# frozen_string_literal: true

module RepresentativesHelper
end

app/views/representatives/index.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Search for a Representative

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        = form_tag search_representatives_path, method: :get do
            .form-group.row
                .col-md-4
                    %label.col-form-label
                        Enter a location:
                .col-md-6
                    = text_field_tag(:address, nil, class: 'form-control')

            .actions
                = submit_tag 'Search', class: 'btn btn-primary'

app/views/representatives/search.html.haml
.container-fluid
    .row
        .col-md-8.offset-md-2
            .table-responsive-md.pt-5
                %table.table.table-striped.table-hover#events
                    %caption Table of Representatives
                    %thead.thead-dark
                        %tr
                            %th Name
                            %th Office
                            %th Profile
                            %th News Article
                    %tbody
                        - @representatives.each_with_index do |rep, _index|
                            %tr
                                %td= rep.name
                                %td= rep.title
                                %td
                                    = link_to representative_path(rep), class: 'btn btn-primary' do
                                        %i.fas.fa-person
                                        Profile
                                %td
                                    = link_to representative_news_items_path(rep.id), class: 'btn btn-primary' do
                                        %i.fas.fa-newspaper
                                        News Articles

app/views/representatives/show.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h3.text-center= @representative.name
        .text-center
            %img{ src: @representative.photo_url, class: 'img-fluid mx-auto d-block' }
        .card-body
            .card-text
                %dl.row
                    %dt.col-sm-3.text-md-right OCD ID:
                    %dt.col-sm-9
                        %a{ href: @representative.ocdid }
                            = @representative.ocdid
                %dl.row
                    %dt.col-sm-3.text-md-right Office:
                    %dt.col-sm-9
                        = @representative.title
                %dl.row
                    %dt.col-sm-3.text-md-right Party:
                    %dt.col-sm-9
                        = @representative.party
                %dl.row
                    %dt.col-sm-3.text-md-right Contact Address:
                    %dt.col-sm-9
                        #{@representative.street}   #{@representative.city},
                        #{@representative.state}, #{@representative.zip}