config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
    get '/login' => 'login#login', :as => :login
    get '/login/google', to: redirect('auth/google_oauth2'), as: :google_login
    get '/login/github', to: redirect('auth/github'), as: :github_login
    get '/auth/google_oauth2/callback', to: 'login#google_oauth2', as: :google_oauth2_callback
    get '/auth/github/callback', to: 'login#github', as: :github_callback
    get '/logout' => 'login#logout', :as => :logout
    get '/user/profile', to: 'user#profile', as: :user_profile

    root to: 'map#index', as: 'root'
    get '/state/:state_symbol' => 'map#state', :as => :state_map
    get '/state/:state_symbol/county/:std_fips_code' => 'map#county', :as => :county
    get '/ajax/state/:state_symbol' => 'ajax#counties'

    # Routes for Events
    resources :events, only: %i[index show]
    get '/my_events/new' => 'my_events#new', :as => :new_my_event
    match '/my_events/new', to: 'my_events#create', via: [:post]
    get '/my_events/:id' => 'my_events#edit', :as => :edit_my_event
    match '/my_events/:id', to: 'my_events#update', via: %i[put patch]
    match '/my_events/:id', to: 'my_events#destroy', via: [:delete]

    # Routes for Representatives
    resources :representatives, only: [:index]
    resources :representatives do
        resources :news_items, only: %i[index show]
        # get '/representatives/:representative_id/my_news_item/new' => 'my_news_items#select_rep_issue', 
        #                                                            => :select_rep_issue #v3
        get '/representatives/:representative_id/my_news_item/new' => 'my_news_items#new', 
            :as                                                        => :new #v1
        # get '/representatives/:representative_id/my_news_item/new/search' => 'my_news_items#search',
        #     :as                                                        => :search #v3
        post '/representatives/:representative_id/my_news_item/new' => 'my_news_items#search',
        :as                                                        => :search #v1
        get '/representatives/:representative_id/my_news_item/new/top_articles' => 'my_news_items#top_articles',
            :as                                                        => :top_articles #v1
        post '/representatives/:representative_id/my_news_item/new/top_articles' => 'my_news_items#rate_article',
            :as                                                        => :rate_article #v1
        #post '/representatives/:representative_id/my_news_item', to: 'my_news_items#create' 
    
        # get 'my_news_item/new', to: 'my_news_items#select_rep_issue', as: :select_rep_issue 
        # get 'my_news_item/new/top_articles', to: 'my_news_items#top_articles', as: :top_articles #v3
        # get 'my_news_item/new/continue', to: 'my_news_items#new_rep_issue', as: :new_rep_issue #v3
        # post 'my_news_item', to: 'my_news_items#create' #v3
  
        # get '/representatives/:representative_id/my_news_item/new' => 'my_news_items#new',
        #     :as                                                    => :new_my_news_item #v3
        #match '/representatives/:representative_id/my_news_item/new', to:  'my_news_items#create',
        #                                                              via: [:post] #v3
        get '/representatives/:representative_id/my_news_item/:id' => 'my_news_items#edit',
            :as                                                    => :edit_my_news_item #v2
        # match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#update',
        #                                                               via: %i[put patch] #v3
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#destroy',
                                                                      via: [:delete] #v2
    end
    get '/search/(:address)' => 'search#search', :as => 'search_representatives'
end

app/controllers/map_controller.rb
# frozen_string_literal: true

require 'google/apis/civicinfo_v2'

class MapController < ApplicationController
  # Render the map of the United States.
  def index
    @states = State.all
    @states_by_fips_code = @states.index_by(&:std_fips_code)
  end

  # Render the map of the counties of a specific state.
  def state
    @state = State.find_by(symbol: params[:state_symbol].upcase)
    handle_state_not_found && return if @state.nil?

    @county_details = @state.counties.index_by(&:std_fips_code)
  end

  # Render the map of a specific county.
  def county
    @state = State.find_by(symbol: params[:state_symbol].upcase)
    handle_state_not_found && return if @state.nil?

    @county = get_requested_county @state.id
    handle_county_not_found && return if @county.nil?

    @county_details = @state.counties.index_by(&:std_fips_code)
    @address = "#{@county.name}, #{params[:state_symbol]}"
    service = Google::Apis::CivicinfoV2::CivicInfoService.new
    service.key = Rails.application.credentials[:GOOGLE_API_KEY]
    result = service.representative_info_by_address(address: @address)
    @representatives = Representative.civic_api_to_representative_params(result)
  end

  private

  def handle_state_not_found
    state_symbol = params[:state_symbol].upcase
    redirect_to root_path, alert: "State '#{state_symbol}' not found."
  end

  def handle_county_not_found
    state_symbol = params[:state_symbol]
    std_fips_code = params[:std_fips_code]
    redirect_to root_path, alert: "County with code '#{std_fips_code}' not found for #{state_symbol}"
  end

  def get_requested_county(state_id)
    County.find_by(
      state:     state_id,
      fips_code: params[:std_fips_code].to_i(10)
    )
  end
end

app/views/map/county.html.haml
.row
    .col-12
        %section.my-4
            %h2.text-center
                = `#{@county.name}, #{@state.symbol}`
            .overflow-hidden.bg-light.text-center.mb-3
                .overflow-auto.py-3
                    %svg.d-inline#actionmap-state-counties-view{ version: 1.1, xmlns: 'http://www.w3.org/2000/svg' }
                        %title  Map of #{@state.name} highlighting #{@county.name}
                        /* SVG element will be filled using d3.js and a topojson file. */

.row
    .col-12.col-lg-8.offset-lg-2
        #actionmap-county-reps-details
            .card
                .card-header#actionmap-reps-details-header
                    %h3.text-center
                        %button.btn.btn-link.collapsed{ 'data-toggle': 'collapse',
                                    'data-target': '#actionmap-counties-details-collapse',
                                    'aria-expanded': false,
                                    'aria-controls': 'actionmap-counties-details-collapse' } |
                            Representatives in #{@county.name}, #{@state.name}
                .collapse#actionmap-counties-details-collapse{ 'data-parent': '#actionmap-reps-details-header',
                'aria-labelledby': '#actionmap-reps-details-header' }
                    .card-body
                        .table-responsive-md
                            %table.table.table-striped.table-hover#actionmap-county-reps-table
                                %caption Table of Representatives in #{@county.name}, #{@state.name}
                                %thead.thead-dark
                                    %tr
                                        %th Name
                                        %th Office
                                        %th Profile
                                        %th News Article
                                %tbody
                                    - @representatives.each_with_index do |rep, _index|
                                        %tr
                                            %td= rep.name
                                            %td= rep.title
                                            %td
                                                = link_to representative_path(rep),
                                                class: 'btn btn-primary' do
                                                    %i.fas.fa-person
                                                    Profile
                                            %td
                                                = link_to representative_news_items_path(rep.id),
                                                class: 'btn btn-primary' do
                                                    %i.fas.fa-newspaper
                                                    News Articles
#actionmap-info-box
.d-none#actionmap-info-container{ 'data-counties': @county_details.to_json, 'data-state': @state.to_json,
'data-state-topojson-file': asset_path("states/#{@state[:symbol].downcase}.topo.json"),
'county-std-fips-code': @county.std_fips_code }
= javascript_pack_tag 'county_map', 'data-turbolinks-track': 'reload'

app/views/map/index.html.haml
.row
    .col-12
        %section.mt-4#actionmap-national-section
            %h2.text-center National Map
            .overflow-hidden.bg-light.text-center.mb-3
                .overflow-auto.py-3
                    %svg.d-block.mx-auto#actionmap-national-view{ height: '600px', width: '960px',
                     xmlns: 'http://www.w3.org/2000/svg' }
                    %title Map of US states
                    /* SVG element will be filled using d3.js and a topojson file. */
/** div displays the details for each state when user hovers over the state region on the map. **/
#actionmap-info-box
.d-none#actionmap-info-container{ 'data-states-topojson-file': asset_path('national/states/us-states.topo.json') }

= javascript_pack_tag 'national_states_map', 'data-turbolinks-track': 'reload'

app/views/map/state.html.haml
%section.my-4
    %h2.text-center
        = @state.name
    .overflow-hidden.bg-light.text-center.mb-3
        .overflow-auto.py-3
            %svg.d-inline#actionmap-state-counties-view{ version: 1.1, xmlns: 'http://www.w3.org/2000/svg' }
                %title  Map of #{@state.name}
                /* SVG element will be filled using d3.js and a topojson file. */
.row
    .col-12.col-lg-8.offset-lg-2
        #actionmap-state-counties-details
            .card
                .card-header#actionmap-counties-details-header
                    %h3.text-center
                        %button.btn.btn-link.collapsed{ 'data-toggle': 'collapse',
                        'data-target': '#actionmap-state-details-collapse', 'aria-expanded': false,
                        'aria-controls': 'actionmap-state-details-collapse' } Counties in #{@state.name}
                .collapse#actionmap-state-details-collapse{ 'data-parent': '#actionmap-counties-details-header',
                'aria-labelledby': '#actionmap-counties-details-header' }
                    .card-body
                        .table-responsive-md
                            %table.table.table-striped.table-hover#actionmap-state-counties-table
                                %caption Table of Counties in #{@state.name}
                                %thead.thead-dark
                                    %tr
                                        %th #
                                        %th Name
                                        %th FIPS Code
                                        %th View
                                %tbody
                                    - @state.counties.each_with_index do |county, index|
                                        %tr
                                            %td= index + 1
                                            %td= county.name
                                            %td= county.std_fips_code
                                            %td
                                                = link_to 'View', county_path(state_symbol: @state.symbol,
                                                std_fips_code: county.std_fips_code),
                                                class: 'btn btn-primary'
#actionmap-info-box
#actionmap-info-container{ 'data-counties': @county_details.to_json, 'data-state': @state.to_json,
'data-state-topojson-file': asset_path("states/#{@state[:symbol].downcase}.topo.json") }
= javascript_pack_tag 'state_map', 'data-turbolinks-track': 'reload'